// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateTruthTable(arg1, arg2) {
  return window['go']['main']['App']['CalculateTruthTable'](arg1, arg2);
}

export function ExtractVariables(arg1) {
  return window['go']['main']['App']['ExtractVariables'](arg1);
}
