// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function CalculateTruthTable(arg1:string,arg2:Record<string, boolean>):Promise<Array<lib.TruthTableEntry>>;

export function ExtractVariables(arg1:string):Promise<Array<string>>;
